services:
  backend:
    build: ./backend
    container_name: petshop-backend
    ports:
      - "3002:3000"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development
      - DB_HOST=pgsql
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres

  frontend:
      build:
        context: ./frontend
        # Usaremos um Dockerfile otimizado para desenvolvimento
        dockerfile: Dockerfile.dev
      container_name: petshop-frontend
      ports:
        - "3001:5173" # A porta do Vite é 5173, não 80
      volumes:
        # Mapeia o código-fonte e os node_modules para dentro do container
        - ./frontend:/app
        - /app/node_modules
      environment:
        - CHOKIDAR_USEPOLLING=true

  pgsql:
    image: postgres:12.17
    container_name: pgsql
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  pgdata: