services:
  backend:
    build: ./backend
    container_name: petshop-backend
    ports:
      - "3002:3000"
    volumes:
      - ./backend:/app
    depends_on:
      - frontend
      - pgsql
    environment:
      - NODE_ENV=development
      - DB_HOST=pgsql
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres

  frontend:
    build: ./frontend
    container_name: petshop-frontend
    ports:
      - "3001:80"
    environment:
      - CHOKIDAR_USEPOLLING=true

  pgsql:
    image: postgres:12.17
    container_name: pgsql
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  pgdata: