version: '3.3'

services:
  backend:
    build: ./backend
    container_name: petshop-backend
    ports:
      - "3002:3000"
    volumes:
      - ./backend:/app
    depends_on:
      - frontend
    environment:
      - NODE_ENV=development

  frontend:
    build: ./frontend
    container_name: petshop-frontend
    ports:
      - "3001:80"
    volumes:
      - ./frontend:/usr/share/nginx/html

    environment:
      - CHOKIDAR_USEPOLLING=true
